language: node_js
node_js: node

script:
    - npm run listdiff
    - npm run lint
    - if [ "$TRAVIS_TAG" ]; then make deploy; else make build; fi

before_deploy:
    - touch ./build/.nojekyll

deploy:
    - provider: npm
      skip-cleanup: true
      email: $NPM_EMAIL
      api_key: $NPM_AUTH_TOKEN
      on:
          repo: magic-akari/lrc-maker
          branch: master
          tags: true

    - provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      local-dir: build
      on:
          branch: master

    - provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      local-dir: build
      repo: lrc-maker/lrc-maker.github.io
      target-branch: master
      on:
          repo: magic-akari/lrc-maker
          branch: master
          tags: true
