language: node_js
node_js: node
script: npm run build
before_deploy: touch ./dist/.nojekyll
deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  repo: lrc-maker/lrc-maker.github.io
  target-branch: master
  on:
    branch: master
