name: Release https://lrc-maker.github.io and npm

on:
    push:
        tags:
            - "v*"

jobs:
    deploy:
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14

            - run: npm ci --ignore-scripts
            - run: npm run listdiff
            - run: npm run lint
            - run: make deploy

            - name: Publish NPM
              run: npm publish --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

            - name: Deploy to lrc-maker.github.io
              uses: peaceiris/actions-gh-pages@v3
              with:
                  personal_token: ${{ secrets.GHP_TOKEN }}
                  external_repository: lrc-maker/lrc-maker.github.io
                  publish_branch: master
                  publish_dir: ./build
                  force_orphan: true
